### ISSUE TITLE
[Q] Adding additional completion sources

### ISSUE THREAD

**Issue by Rikorose** [haorenW1025/completion-nvim#15]
Thanks for your nice and lightweight plugin!

It realy works great with nvim-lsp. I would like to integrate additional completion sources like other words in the current or other buffers, or from different tmux panes. Is there already support for these kind of sources? How can I include these?

**Comment by haorenW1025** [comment]
Thanks for the kind words!
Right now I'd said that additional sources can definitely be integrated but it could be tedious because I haven't create a proper way for other to easily to that. Moreover the lsp completion is working in an asynchronously, making it harder to control it(I've been working on solving that lately). I think the ultimate goal is to support other sources like ![asyncomplete-vim](https://github.com/prabirshrestha/asyncomplete.vim) did. If you're interesting in creating custom source you can first take a look at `source.lua`, `source/ts_complete.lua` and `source/snippet.lua`.
By the way, I'm also working on chaining completion like ![mu-complete](https://github.com/lifepillar/vim-mucomplete)(follow this ![issue](https://github.com/haorenW1025/completion-nvim/issues/4)) and ins-complete integration. I think other words in the current or other buffers can be done with ins-complete(with `<c-n>` and `<c-p>`).
If you have further question or some suggestion free feel to ask me here! Thanks!

**Comment by haorenW1025** [comment]
Adding additional completion source is now possible! See this ![wiki](https://github.com/haorenW1025/completion-nvim/wiki/custom-completion-source) for example. Feel free to ask me if you have any question!
