### ISSUE TITLE
[Feature Request] Customizing completion kind labels

### ISSUE THREAD

**Issue by wbthomason** [haorenW1025/completion-nvim#36]
It would be nice if, similar to `coc.nvim`, there was an easy way to customize the labels used for various kinds of items in completion results. The most common use case of this is probably wanting to use icons rather than names for the labels.

**Comment by haorenW1025** [comment]
Nice Suggestion! You can try setting it up in the latest version by
```.vim
let g:completion_customize_lsp_label = {
                \ 'Text' : '...',
                \ 'Function': '...',
                \}
```

**Comment by wbthomason** [comment]
Thanks!

Closed in feb81cc

**Comment by clason** [comment]
Nice feature, and definitely useful. Two remarks:

1. It'd be good to document it in the README

2. Even more useful would be to allow customization on a per-server basis (since for some servers -- such as texlab -- the default labels are not a good fit at all). 

Of course, point 2 would require much more intrusive changes (passing the server name or a label struct through the various completion callbacks). Ideally, this would be supported by the core neovim LSP (and configured as part of the server configuration through nvim-lsp, together with the corresponding customization of `symbolKind`s).

**Comment by clason** [comment]
Oh, and question (to @wbthomason as well): would it be more convenient to map directly to the enum (i.e., via `'1': 'string'` instead of `'Function': 'string'`)?

**Comment by haorenW1025** [comment]
>  1. It'd be good to document it in the README

Definitely, I not having a good habits of updating README for every features...
> 2. Even more useful would be to allow customization on a per-server basis (since for some servers -- such as texlab -- the default labels are not a good fit at all).

I think customizing `kind` labels per server might not be a good idea (at least in `completion-nvim` since that would be a little tedious to work with.

> Oh, and question (to @wbthomason as well): would it be more convenient to map directly to the enum (i.e., via '1': 'string' instead of 'Function': 'string')?

I set it up this way because is more intuitive for users to set up. Since the `Function` label is already on the completion menu, so users won't have to look up to LSP spec for knowing what to put in.

**Comment by clason** [comment]
> I think customizing kind labels per server might not be a good idea (at least in completion-nvim since that would be a little tedious to work with.

Sure, I understand that, but I do think making it per-server is the better option in the long run (because some customizations only make sense for specific servers). That would be better done in the neovim core, as I wrote -- I'm planning to open an issue about this there soon.

**Comment by clason** [comment]
Actually, I just found out that it's _really_ easy to customize that on the neovim side: just put something like
```lua
local protocol = require'vim.lsp.protocol'
protocol.CompletionItemKind[22] = 'book'
```
before the nvim-lsp `setup` function. (The same works for `SymbolKind`.) No (other) messing with the callbacks required! 

(Maybe be saving the dict and restoring after setup, it's possible to do this on a per-server basis?)

**Comment by haorenW1025** [comment]
@clason I think the only way to enable per-server base customize label is through the `on_attach` function. I've made an update and you can pass in customize label like this
```lua
local on_attach_vim = function()
  require'completion'.on_attach()
  require'diagnostic'.on_attach()
  require'completion'.customisze_buf_label({
      Text = "vim_text",
      Function = "vim_func",
      Method = "vim_method",
      Variable = "vim_variable"
    })
end

local on_attach_lua = function()
  require'completion'.on_attach()
  require'diagnostic'.on_attach()
  require'completion'.customisze_buf_label({
      Text = "lua_text",
      Function = "lua_func",
      Method = "lua_method",
      Variable = "lua_variable"
    })
end

lsp.vimls.setup{
  on_attach = on_attach_vim;
}

lsp.sumneko_lua.setup{
  on_attach= on_attach_lua;
}
```
`customize_buf_label` only set up buffer variable so it won't override other client. It is more tedious to set up though, maybe this is a valid solution if neovim's core doesn't want to expose the protocol functions.

**Comment by clason** [comment]
I think that's a very reasonable approach. 👍 

(I still think that core is the better place to change it so it'll also apply to omnicomplete and allow for symbol kind customization, but my impression is that the maintainers want to keep the "user-facing" LSP functionality minimal and rely on users overriding (i.e., modifying copy-pasted functions) in their init.vim instead of adding configurability.)
