### ISSUE TITLE
Understanding NeoVim completion and your plugin

### ISSUE THREAD

**Issue by nomasprime** [haorenW1025/completion-nvim#61]
Would like to use NeoVim LSP completion. Came across the [official docs](https://neovim.io/doc/user/lsp.html) and your solution which seems to be the only completion plugin using the native LSP client.

I don't know much about NeoVim completions so I'm just trying to find my way. I have a couple of questions:

1. What are the differences between the setup in the core docs and your plugin?
2. NeoVim seems to have multiple completions (word, line, file, omni). It seems like any completion plugin, including yours, takes over the word completion and makes it behave more like omni but I've noticed in your [dotfiles](https://github.com/haorenW1025/dotfiles/blob/master/nvim/config/plugin-setting.vim#L5) that you're still using settings relating to omni. Does this mean omni is still relevant and what's the relationship between the two?

Would really appreciate some guidance, in the meantime I'll continue to educate myself.

**Comment by haorenW1025** [comment]
> What are the differences between the setup in the core docs and your plugin?

You still need to follow the setup in the core docs in order to use this plugins. This plugin simply take the completion items that comes from the native LSP and use it with an auto completion manners.

> NeoVim seems to have multiple completions (word, line, file, omni). It seems like any completion plugin, including yours, takes over the word completion and makes it behave more like omni but I've noticed in your dotfiles that you're still using settings relating to omni. Does this mean omni is still relevant and what's the relationship between the two?

I don't actually use the omni completion myself because the completion items should be almost equivalent if you use `completion-nvim`, just haven't remove it from my dotfiles though. The omni complete of native lsp use almost the same strategy of `completion-nvim` which takes in LSP suggestion and display it in omni completion. Also I didn't take over the word completion, you can still use `<ctrl-n>` or `<ctrl-p>` or anything you want from the built-in completion. Actually with `completion-nvim`, you can setup backup completion sources. You can configure it to switch sources if the current source have no completion items or manually switching it(see [wiki](https://github.com/haorenW1025/completion-nvim/wiki/chain-complete-support) from instructions). If you're still very confusing, feel free to join us in [gitter](https://gitter.im/completion-nvim/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge):)

**Comment by nomasprime** [comment]
Thanks @haorenW1025 I will add on Gitter.
