### ISSUE TITLE
Add config for min characters before invoking

### ISSUE THREAD

**Issue by nhooyr** [haorenW1025/completion-nvim#97]
e.g. https://github.com/neoclide/coc.nvim/blob/b19060c1831dfc38ece7ea1cba976dbc5c56c8fc/doc/coc.txt#L223-L226

**Comment by haorenW1025** [comment]
Try setting
```vim
let g:completion_trigger_keyword_length = 3 " default is 1
```
That's not documented though...

**Comment by nhooyr** [comment]
Awesome!

Yea, just needs documentation then.

**Comment by nhooyr** [comment]
Doesn't seem to work for me fully.

If I'm in my `init.vim` and type:

```
"|
```

The autocompletion menu pops up still.

**Comment by nhooyr** [comment]
`|` being my cursor.

**Comment by nhooyr** [comment]
Seems to work fine for words though. I guess completion always triggers on symbols so that `i.|` for example always shows i's methods?

**Comment by haorenW1025** [comment]
That's because `completion-nvim` respect server's trigger character. You can see the the trigger character by 
`:lua print(vim.inspect(vim.lsp.buf_get_clients([1].server_capabilities.completionProvider.triggerCharacters))`
When hitting keys on these tigger character, completion will be triggered and it doesn't care about the keyword length.

**Comment by nhooyr** [comment]
Makes sense. All's good then.

**Comment by haorenW1025** [comment]
Documentation is up🚀 Close it for now:)
